package command;

public enum CommandType {
    CREATE_CLIENT,
    CREATE_STAFF,
    VIEW_STAFF,
    DELETE_CLIENT,
    DELETE_STAFF,
    EDIT_CLIENT,
    VIEW_CLIENTS,
    CREATE_APPOINTMENT,
    EDIT_APPOINTMENT,
    VIEW_ALL_APPOINTMENTS,
    VIEW_CLIENT_APPOINTMENTS,

    EXIT,

    UNDEFINED
}
