package command;

public enum CommandType {
    CREATE_CLIENT,
    CREATE_STAFF,
    VIEW_STAFF,
    DELETE_CLIENT,
    DELETE_STAFF,
    EDIT_CLIENT,
    VIEW_CLIENTS,
    CREATE_APPOINTMENT,
    EDIT_APPOINTMENT,
    VIEW_ALL_APPOINTMENTS,
    VIEW_CLIENT_APPOINTMENTS,
    CREATE_FOLDER,
    CREATE_NOTE,
    FOLDER_AND_NOTE_VIEWER,
    MOVE_TO_OTHER_FOLDER,
    MOVE_FOLDER_UP,
    FIND_USERS_NOTE_WITH_PATH,

    EXIT,

    UNDEFINED
}
