package command;

public enum CommandType {
    CREATE_USER,
    VIEW_STAFF,
    DELETE_USER,
    EDIT_USER,
    VIEW_USERS,
    CREATE_APPOINTMENT,
    EDIT_APPOINTMENT,
    VIEW_CLIENT_APPOINTMENTS,
    CREATE_FOLDER,
    CREATE_NOTE,
    FOLDER_AND_NOTE_VIEWER,
    MOVE_TO_OTHER_FOLDER,
    MOVE_FOLDER_UP,
    FIND_All_USERS_NOTE_WITH_PATH,
    FIND_USERS_NOTE_WITH_PATH,

    UNDEFINED
}
